title: Living Water 活水FM
description: 「活水fm」是由加拿大女王大学校园团契----活水团契的一群基督徒们出品的访谈聊天类的播客节目。我们的目标是从生活中观察到的每一件事中去体会圣经的含义和预示，希望带给听众朋友们我们自己关于圣经的理解和体会，以及上帝在我们生命中的带领和改变。希望在这里，你能被鼓励，被理解，被安慰，被爱。
author: Living Water Fellowship at KCAC
email: LivingWater.QU@gmail.com
lang: en-us
copyright: Kingston Chinese Alliance Church, All right reserved
logo: /assets/img/lvfm.jpg

exclude:
  - Gemfile
  - Gemfile.lock
